language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -r client/requirements.txt -r server/requirements.txt -r
    requirements_dev.txt
script:
  - python -m pytest
  - flake8
